server:
  port: 8092

spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: 10.10.10.60:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: abcd-group-1
      properties:
        spring.json.trusted.packeages: "*"
        spring.json.use.type.headers: false

logging:
  level:
    org.example.consumer: debug