server:
  port: 8091

spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: 10.10.10.60:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: abcd-group-1

logging:
  level:
    org.example.producer: debug