server:
  port: 8091

spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: 10.10.10.60:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.example.producer: debug